"""Add WhatsApp session columns to SolicitudCita

Revision ID: 1a4c94f2174e
Revises: f6180b18085b
Create Date: 2025-10-30 15:03:40.704034

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a4c94f2174e'
down_revision = 'f6180b18085b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp_step', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_last_activity', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_timeout_minutes', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_warning_sent', sa.Boolean(), nullable=True))
        batch_op.drop_column('ultimo_recordatorio')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_recordatorio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('whatsapp_warning_sent')
        batch_op.drop_column('whatsapp_timeout_minutes')
        batch_op.drop_column('whatsapp_last_activity')
        batch_op.drop_column('whatsapp_step')

    # ### end Alembic commands ###
