"""Add post_confirmation_messages field to SolicitudCita

Revision ID: 70448fbd0dde
Revises: c2f0e80509f7
Create Date: 2025-10-30 11:48:24.860196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70448fbd0dde'
down_revision = 'c2f0e80509f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_confirmation_messages', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_cita', schema=None) as batch_op:
        batch_op.drop_column('post_confirmation_messages')

    # ### end Alembic commands ###
