"""Add celular to SolicitudCita

Revision ID: 99ff412b79ea
Revises: 
Create Date: 2025-10-28 16:14:59.280561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '99ff412b79ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('enturne_historial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enturne_historial_empresa'))
        batch_op.drop_index(batch_op.f('ix_enturne_historial_enturne_id'))
        batch_op.drop_index(batch_op.f('ix_enturne_historial_guia'))
        batch_op.drop_index(batch_op.f('ix_enturne_historial_placa'))
        batch_op.drop_index(batch_op.f('ix_enturne_historial_planilla_tipo'))
        batch_op.drop_index(batch_op.f('ix_enturne_historial_snapshot_at'))

    op.drop_table('enturne_historial')
    with op.batch_alter_table('vehiculo_cargue_registros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiculo_cargue_registros_estado'))
        batch_op.drop_index(batch_op.f('ix_vehiculo_cargue_registros_guia_unica'))
        batch_op.drop_index(batch_op.f('ix_vehiculo_cargue_registros_planilla_tipo'))
        batch_op.drop_index(batch_op.f('ix_vehiculo_cargue_registros_timestamp'))

    op.drop_table('vehiculo_cargue_registros')
    with op.batch_alter_table('vehiculo_cargue_historial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehiculo_cargue_historial_estado'))
        batch_op.drop_index(batch_op.f('ix_vehiculo_cargue_historial_guia_unica'))
        batch_op.drop_index(batch_op.f('ix_vehiculo_cargue_historial_planilla_tipo'))
        batch_op.drop_index(batch_op.f('ix_vehiculo_cargue_historial_registro_id'))
        batch_op.drop_index(batch_op.f('ix_vehiculo_cargue_historial_snapshot_at'))

    op.drop_table('vehiculo_cargue_historial')
    with op.batch_alter_table('enturne_registros', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_enturne_registros_guia'))
        batch_op.drop_index(batch_op.f('ix_enturne_registros_placa'))
        batch_op.drop_index(batch_op.f('ix_enturne_registros_planilla_tipo'))
        batch_op.drop_index(batch_op.f('ix_enturne_registros_timestamp'))

    op.drop_table('enturne_registros')
    with op.batch_alter_table('transito_historial', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transito_historial_snapshot_at'))
        batch_op.drop_index(batch_op.f('ix_transito_historial_tipo_transito'))
        batch_op.drop_index(batch_op.f('ix_transito_historial_transito_id'))

    op.drop_table('transito_historial')
    op.drop_table('conversacion_whatsapp')
    with op.batch_alter_table('registros_barcaza_orion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_barcaza_orion_empresa'))
        batch_op.drop_column('empresa')

    with op.batch_alter_table('registros_transito', schema=None) as batch_op:
        batch_op.drop_column('empresa')

    with op.batch_alter_table('registros_zisa', schema=None) as batch_op:
        batch_op.drop_column('cliente')
        batch_op.drop_column('m3')
        batch_op.drop_column('cierre_dex')
        batch_op.drop_column('codigo_siza')
        batch_op.drop_column('gals_netos')
        batch_op.drop_column('toneladas_netas')
        batch_op.drop_column('kg')
        batch_op.drop_column('dex')
        batch_op.drop_column('subpartida')
        batch_op.drop_column('formulario_ingreso_zf')
        batch_op.drop_column('numero_remision')
        batch_op.drop_column('selectividad_fisica')
        batch_op.drop_column('fecha_descargue')
        batch_op.drop_column('fecha_remision')
        batch_op.drop_column('planilla_traslado')

    with op.batch_alter_table('solicitudes_cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celular', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_cita', schema=None) as batch_op:
        batch_op.drop_column('celular')

    with op.batch_alter_table('registros_zisa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planilla_traslado', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_remision', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_descargue', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('selectividad_fisica', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('numero_remision', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('formulario_ingreso_zf', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subpartida', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dex', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('toneladas_netas', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('gals_netos', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('codigo_siza', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cierre_dex', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('m3', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cliente', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    with op.batch_alter_table('registros_transito', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa', sa.VARCHAR(length=32), autoincrement=False, nullable=True))

    with op.batch_alter_table('registros_barcaza_orion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_registros_barcaza_orion_empresa'), ['empresa'], unique=False)

    op.create_table('conversacion_whatsapp',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('telefono', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('mensaje', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('fecha', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('solicitud_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_cita.id'], name=op.f('conversacion_whatsapp_solicitud_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('conversacion_whatsapp_pkey'))
    )
    op.create_table('transito_historial',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('accion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('transito_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo_transito', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('origen', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('fecha', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('guia', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('producto', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('placa', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('api', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bsw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nsv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('transito_historial_pkey'))
    )
    with op.batch_alter_table('transito_historial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transito_historial_transito_id'), ['transito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transito_historial_tipo_transito'), ['tipo_transito'], unique=False)
        batch_op.create_index(batch_op.f('ix_transito_historial_snapshot_at'), ['snapshot_at'], unique=False)

    op.create_table('enturne_registros',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('planilla_tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('placa', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('guia', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('campo', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('fecha_enturne', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_llegada', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('hora_llegada', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('fecha_descargo', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('turno', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('cio', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('numero_manifiesto', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('autorizacion_manifiesto', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('numero_formulario', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sae_numero', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('codigo_factura', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('enturne_registros_pkey')),
    sa.UniqueConstraint('planilla_tipo', 'placa', 'guia', name=op.f('uq_enturne_tipo_placa_guia'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('enturne_registros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enturne_registros_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_enturne_registros_planilla_tipo'), ['planilla_tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_enturne_registros_placa'), ['placa'], unique=False)
        batch_op.create_index(batch_op.f('ix_enturne_registros_guia'), ['guia'], unique=False)

    op.create_table('vehiculo_cargue_historial',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('accion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('registro_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planilla_tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('empresa', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('fecha_cargue', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('hora_salida', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('guia_unica', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('empresa_transportadora', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('campo', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('cedula_conductor', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nombre_conductor', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('celular_conductor', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('placa_vehiculo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('placa_tanque', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('api', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bsw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bls_bruto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bls_gsv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bls_nsv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ubicacion', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vehiculo_cargue_historial_pkey'))
    )
    with op.batch_alter_table('vehiculo_cargue_historial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehiculo_cargue_historial_snapshot_at'), ['snapshot_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculo_cargue_historial_registro_id'), ['registro_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculo_cargue_historial_planilla_tipo'), ['planilla_tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculo_cargue_historial_guia_unica'), ['guia_unica'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculo_cargue_historial_estado'), ['estado'], unique=False)

    op.create_table('vehiculo_cargue_registros',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('planilla_tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('empresa', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('fecha_cargue', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('hora_salida', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('guia_unica', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('empresa_transportadora', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('campo', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('cedula_conductor', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nombre_conductor', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('celular_conductor', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('placa_vehiculo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('placa_tanque', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('api', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bsw', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bls_bruto', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bls_gsv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bls_nsv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ubicacion', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('vehiculo_cargue_registros_pkey'))
    )
    with op.batch_alter_table('vehiculo_cargue_registros', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehiculo_cargue_registros_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculo_cargue_registros_planilla_tipo'), ['planilla_tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculo_cargue_registros_guia_unica'), ['guia_unica'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehiculo_cargue_registros_estado'), ['estado'], unique=False)

    op.create_table('enturne_historial',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('snapshot_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('accion', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('enturne_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('planilla_tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('placa', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('guia', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('campo', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('fecha_enturne', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('fecha_llegada', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('hora_llegada', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('fecha_descargo', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('turno', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('notas', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('empresa', sa.VARCHAR(length=150), autoincrement=False, nullable=True),
    sa.Column('bls_nsv', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('cio', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('numero_manifiesto', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('autorizacion_manifiesto', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('numero_formulario', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sae_numero', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('codigo_factura', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('enturne_historial_pkey'))
    )
    with op.batch_alter_table('enturne_historial', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_enturne_historial_snapshot_at'), ['snapshot_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_enturne_historial_planilla_tipo'), ['planilla_tipo'], unique=False)
        batch_op.create_index(batch_op.f('ix_enturne_historial_placa'), ['placa'], unique=False)
        batch_op.create_index(batch_op.f('ix_enturne_historial_guia'), ['guia'], unique=False)
        batch_op.create_index(batch_op.f('ix_enturne_historial_enturne_id'), ['enturne_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_enturne_historial_empresa'), ['empresa'], unique=False)

    # ### end Alembic commands ###
