"""Add ZISA GPS fields and ruta_alterna

Revision ID: c2f0e80509f7
Revises: e41fe7b8eea1
Create Date: 2025-10-30 11:01:38.400733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2f0e80509f7'
down_revision = 'e41fe7b8eea1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion_zisa_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ubicacion_zisa_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('paso_zisa', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ruta_alterna', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_cita', schema=None) as batch_op:
        batch_op.drop_column('ruta_alterna')
        batch_op.drop_column('paso_zisa')
        batch_op.drop_column('ubicacion_zisa_lng')
        batch_op.drop_column('ubicacion_zisa_lat')

    # ### end Alembic commands ###
