"""Add Gambote GPS fields

Revision ID: e41fe7b8eea1
Revises: 99ff412b79ea
Create Date: 2025-10-30 10:14:49.264564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e41fe7b8eea1'
down_revision = '99ff412b79ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion_gambote_lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ubicacion_gambote_lng', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('paso_gambote', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_cita', schema=None) as batch_op:
        batch_op.drop_column('paso_gambote')
        batch_op.drop_column('ubicacion_gambote_lng')
        batch_op.drop_column('ubicacion_gambote_lat')

    # ### end Alembic commands ###
