"""add ultimo_recordatorio field

Revision ID: f6180b18085b
Revises: 70448fbd0dde
Create Date: 2025-10-30 14:14:40.796912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6180b18085b'
down_revision = '70448fbd0dde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_cita', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ultimo_recordatorio', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_cita', schema=None) as batch_op:
        batch_op.drop_column('ultimo_recordatorio')

    # ### end Alembic commands ###
